#version: 2.1
#workflows:
#  testing:
#    jobs:
#      - runner-test
#jobs:
#  runner-test:
#    machine: true
#    resource_class: syedibrahim/test1
#    steps:
#      - run: echo "Hi I'm on Runners!"

# .circleci/config.yml

version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            choco install nodejs --version 14.17.3 -y

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run project
          command: npm start
